In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets  
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import  DecisionTreeClassifier
from sklearn import tree
from sklearn.metrics import classification_report
from sklearn import preprocessing

In [28]:
data=pd.read_csv('C:\\Users\\vishw\\excelr drive files\\Assignments questions of excelr\\Decision_Trees\\Fraud_check.csv')
data

Undergrad Marital.Status  Taxable.Income  City.Population  \
0          NO         Single           68833            50047   
1         YES       Divorced           33700           134075   
2          NO        Married           36925           160205   
3         YES         Single           50190           193264   
4          NO        Married           81002            27533   
..        ...            ...             ...              ...   
595       YES       Divorced           76340            39492   
596       YES       Divorced           69967            55369   
597        NO       Divorced           47334           154058   
598       YES        Married           98592           180083   
599        NO       Divorced           96519           158137   

     Work.Experience Urban  
0                 10   YES  
1                 18   YES  
2                 30   YES  
3                 15   YES  
4                 28    NO  
..               ...   ...  
595                7   YES  
596                2   YES  
597                0   YES  
598               17    NO  
599               16    NO  

[600 rows x 6 columns]

In [8]:
data.head(2)

Undergrad Marital.Status Taxable.Income  City.Population  Work.Experience  \
0        NO         Single          68833            50047               10   
1       YES       Divorced          33700           134075               18   

  Urban  
0   YES  
1   YES

In [9]:
data.drop('Taxable.Income',1,inplace=True)

In [10]:
data['Marital.Status'].value_counts()

Single      217
Married     194
Divorced    189
Name: Marital.Status, dtype: int64

In [11]:
label_encoder = preprocessing.LabelEncoder() 
data['Marital.Status']= label_encoder.fit_transform(data['Marital.Status']) 
data['Marital.Status'].unique() 

array([2, 0, 1])

In [12]:
data.head(2)

Undergrad  Marital.Status  City.Population  Work.Experience Urban
0        NO               2            50047               10   YES
1       YES               0           134075               18   YES

In [13]:
data.Undergrad.value_counts()

YES    312
NO     288
Name: Undergrad, dtype: int64

In [14]:
data['Undergrad']= label_encoder.fit_transform(data['Undergrad']) 
data['Undergrad'].unique() 

array([0, 1])

In [15]:
data.Urban.value_counts()

YES    302
NO     298
Name: Urban, dtype: int64

In [16]:
data['Urban']= label_encoder.fit_transform(data['Urban']) 
data['Urban'].unique() 

array([1, 0])

In [17]:
data.head()

Undergrad  Marital.Status  City.Population  Work.Experience  Urban
0          0               2            50047               10      1
1          1               0           134075               18      1
2          0               1           160205               30      1
3          1               2           193264               15      1
4          0               1            27533               28      0

In [19]:
colnames = list(data.columns)
predictors = colnames[0:5]
target = colnames[4]

In [20]:
predictors

['Undergrad', 'Marital.Status', 'City.Population', 'Work.Experience', 'Urban']

In [21]:
target

'Urban'

# Splitting data into training and testing data set

In [22]:
train,test = train_test_split(data,test_size = 0.2)

In [23]:
model = DecisionTreeClassifier(criterion = 'entropy')
model.fit(train[predictors],train[target])

DecisionTreeClassifier(criterion='entropy')

In [24]:
preds = model.predict(test[predictors])

In [25]:
pd.Series(preds).value_counts()
pd.crosstab(test[target],preds)

col_0   0   1
Urban        
0      60   0
1       0  60