In [27]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import preprocessing 
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix

In [3]:
data=pd.read_csv('C:\\Users\\vishw\\excelr drive files\\Assignments questions of excelr\\Random_Forests\\Company_Data.csv')
data.head()

Sales  CompPrice  Income  Advertising  Population  Price ShelveLoc  Age  \
0   9.50        138      73           11         276    120       Bad   42   
1  11.22        111      48           16         260     83      Good   65   
2  10.06        113      35           10         269     80    Medium   59   
3   7.40        117     100            4         466     97    Medium   55   
4   4.15        141      64            3         340    128       Bad   38   

   Education Urban   US  
0         17   Yes  Yes  
1         10   Yes  Yes  
2         12   Yes  Yes  
3         14   Yes  Yes  
4         13   Yes   No

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   CompPrice    400 non-null    int64 
 1   Income       400 non-null    int64 
 2   Advertising  400 non-null    int64 
 3   Population   400 non-null    int64 
 4   Price        400 non-null    int64 
 5   ShelveLoc    400 non-null    object
 6   Age          400 non-null    int64 
 7   Education    400 non-null    int64 
 8   Urban        400 non-null    object
 9   US           400 non-null    object
 10  sales        400 non-null    object
dtypes: int64(7), object(4)
memory usage: 34.5+ KB


No null values.

In [4]:
data.loc[data.Sales >=8.5,'sales']= 'high'
data.loc[data.Sales <8.5,'sales']= 'low'

In [5]:
data.drop('Sales',1,inplace=True)

In [8]:
data.isnull().sum()

CompPrice      0
Income         0
Advertising    0
Population     0
Price          0
ShelveLoc      0
Age            0
Education      0
Urban          0
US             0
sales          0
dtype: int64

In [10]:
label_encoder = preprocessing.LabelEncoder() 
data['US']= label_encoder.fit_transform(data['US']) 
data['US'].unique() 

array([1, 0])

In [11]:
label_encoder = preprocessing.LabelEncoder() 
data['Urban']= label_encoder.fit_transform(data['Urban']) 

In [12]:
label_encoder = preprocessing.LabelEncoder() 
data['ShelveLoc']= label_encoder.fit_transform(data['ShelveLoc'])

In [13]:
colnames = list(data.columns)
predictors = colnames[0:10]
target = colnames[10]

In [14]:
predictors

['CompPrice',
 'Income',
 'Advertising',
 'Population',
 'Price',
 'ShelveLoc',
 'Age',
 'Education',
 'Urban',
 'US']

In [15]:
target

'sales'

In [16]:
label_encoder = preprocessing.LabelEncoder() 
data['sales']= label_encoder.fit_transform(data['sales']) 

In [17]:
X = data[predictors]
Y = data[target]

In [19]:
rf = RandomForestClassifier(n_jobs=2,oob_score=True,n_estimators=1000,criterion="entropy")

In [20]:
rf.fit(X,Y)

C:\Users\vishw\anaconda3\lib\site-packages\sklearn\base.py:445: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


RandomForestClassifier(criterion='entropy', n_estimators=1000, n_jobs=2,
                       oob_score=True)

In [21]:
rf.estimators_

[DecisionTreeClassifier(criterion='entropy', max_features='auto',
                        random_state=1036090145),
 DecisionTreeClassifier(criterion='entropy', max_features='auto',
                        random_state=1834877614),
 DecisionTreeClassifier(criterion='entropy', max_features='auto',
                        random_state=1777662866),
 DecisionTreeClassifier(criterion='entropy', max_features='auto',
                        random_state=2055886594),
 DecisionTreeClassifier(criterion='entropy', max_features='auto',
                        random_state=1912131196),
 DecisionTreeClassifier(criterion='entropy', max_features='auto',
                        random_state=983613492),
 DecisionTreeClassifier(criterion='entropy', max_features='auto',
                        random_state=1249868114),
 DecisionTreeClassifier(criterion='entropy', max_features='auto',
                        random_state=1499380318),
 DecisionTreeClassifier(criterion='entropy', max_features='auto',
       

In [22]:
rf.classes_

array([0, 1])

In [23]:
rf.n_classes_

2

In [24]:
rf.n_features_

C:\Users\vishw\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:103: FutureWarning: Attribute `n_features_` was deprecated in version 1.0 and will be removed in 1.2. Use `n_features_in_` instead.
  warnings.warn(msg, category=FutureWarning)


10

In [25]:
rf.n_outputs_

1

In [26]:
data['rf_pred'] = rf.predict(X)

# Confusion matrix

In [28]:
confusion_matrix(data['sales'],data['rf_pred'])

array([[143,   0],
       [  0, 257]], dtype=int64)

# Decision Trees

In [29]:
rf = RandomForestClassifier(n_jobs=2,oob_score=True,n_estimators=500,criterion="entropy")

In [30]:
rf.fit(X,Y)

C:\Users\vishw\anaconda3\lib\site-packages\sklearn\base.py:445: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


RandomForestClassifier(criterion='entropy', n_estimators=500, n_jobs=2,
                       oob_score=True)

In [31]:
data['rf_pred2'] = rf.predict(X)

# Confusion matrix

In [32]:
confusion_matrix(data['sales'],data['rf_pred2'])

array([[143,   0],
       [  0, 257]], dtype=int64)